# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Francesco Cremonesi's Blog
email: francesco.cremonesi0@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    I am a PhD student in computational neuroscience and high
    performance computing. My research is currently focused
    on the computational and algorithmic aspects related to simulating
    neural networks. I am interested in machine learning and software
    development. When I'm not yelling at my computer screen, I'm
    either taking travel photos, playing basketball or bullying my
    fingers into playing the guitar.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: checc000
github_username:  sharkovsky

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
